### ISSUE TITLE
Finish Zone cleanup

### ISSUE THREAD

**Issue by SarinaAtkinson-NOAA** [SarinaAtkinson-NOAA/SEFSC-ODM-Management-History#5]
This [xref table](https://docs.google.com/spreadsheets/d/1gVFz6UUiN5LU3Fr9NuFSumKGeHvRubgZviJt7R73Gvg/edit#gid=0) renames some zones if they are duplicates. This table is only cleaning up zone name for Gulf reef fish and all other FMPs need to be added.

- [x] SNAPPER-GROUPER FISHERY OF THE SOUTH ATLANTIC REGION
- [X] REEF FISH RESOURCES OF THE GULF OF MEXICO  
- [x] COASTAL MIGRATORY PELAGIC RESOURCES 
- [x] SPINY LOBSTER FISHERY OF PUERTO RICO AND THE U.S. VIRGIN ISLANDS
- [x] REEF FISH FISHERY OF PUERTO RICO AND THE U.S. VIRGIN ISLANDS
- [x] SPINY LOBSTER FISHERY OF THE GULF OF MEXICO AND SOUTH ATLANTIC 
- [x] RED DRUM FISHERY OF THE GULF OF MEXICO
- [x] SHRIMP FISHERY OF THE GULF OF MEXICO
- [x] DOLPHIN AND WAHOO FISHERY OFF THE ATLANTIC STATES
- [x] GOLDEN CRAB FISHERY OF THE SOUTH ATLANTIC
- [x] ATLANTIC COAST RED DRUM FISHERY
- [x] QUEEN CONCH RESOURCES OF PUERTO RICO AND THE U.S. VIRGIN ISLANDS
- [x] SHRIMP FISHERY OF THE SOUTH ATLANTIC

**Comment by AdyanRios-NOAA** [comment]
Katherine had a summary for us:No Formatting Changes Needed:

Atlantic Coast Red Drum Fishery
Dolphin sand Wahoo Fishery Off the Atlantic States
Golden Crab Fishery of the South Atlantic
Queen Conch Resources of Puerto Rico and the U.S. Virgin Islands
Red Drum Fishery of the Gulf of Mexico
Reef Fish Fishery of Puerto Rico and the U.S. Virgin Islands
Reef Fish Resources of the Gulf of Mexico*
*There were changes that have already been addressed
Shrimp Fishery of the Gulf of Mexico
Shrimp Fishery of the South Atlantic
Spiny Lobster Fishery of the Gulf of Mexico and South Atlantic
Formatting Changes Needed:

Coastal Migratory Pelagic Resources - SATL: Atlantic Migratory Group Spanish Mackerel - South of 30°42'45.6¿ N. Lat.
change to: SATL: Atlantic Migratory Group Spanish Mackerel - South of 30°42'45.6" N. Lat.
Coastal Migratory Pelagic Resources - SATL: Atlantic Migratory Group Spanish Mackerel - Between 29°25' N. Lat and 25°20.24¿ N. Lat.
change to: SATL: Atlantic Migratory Group Spanish Mackerel - Between 29°25' N. Lat and 25°20.24" N. Lat.
Snapper-Grouper Fishery of the South Atlantic Region - SATL: North of Cape Canaveral - Off of North Carolina and South Carolina
remove and replace with existing region:zone of SATL: Off of North Carolina and South Carolina*
*I believe the three records using this zone (REG ID 2050, 2053, and 2252) were entered incorrectly as "Off of North Carolina and South Carolina" is a smaller zone than "North of Cape Canaveral" so the "North of Cape Canaveral" is not a necessary specification
Snapper-Grouper Fishery of the South Atlantic Region - SATL: Off the Southern Atlantic States
remove and replace with existing region:zone of SATL: ALL*
*I believe the record recorded using this zone did so because it is the exact wording of the FR; however, based on my search of the dataset it appears it is the same zone as SATL: ALL (REG ID 1428)
Snapper-Grouper Fishery of the South Atlantic Region - SATL: South of 35°15.9' N. Lat
Snapper-Grouper Fishery of the South Atlantic Region - SATL: South of 35°15.9' N. Lat, Cape Hatteras Light, North Carolina
Snapper-Grouper Fishery of the South Atlantic Region - SATL: South of Cape Hatteras, NC
I believe the above three zones can be consolidated under one name as they all are referencing the same location (REG IDs 1565, 1578, 11507, 11508, 145, 214, 211, 210, and 1605)
Spiny Lobster Fishery pf Puerto Rico and the U.S. Virgin Islands - CAR: St Croix
remove and replace with existing region:zone of CAR: St. Croix Management Area*
*The summary section of the FR using this zone states that the fishing season adjustment is applicable to the St. Croix Management Area (REG ID 37355)
To complete this check I used the Sept 20, 2022 download of the MH Dataset found below.

**Comment by SarinaAtkinson-NOAA** [comment]
New xref table [created](https://docs.google.com/spreadsheets/d/1T7tlLr2wWkwJdRCbanKQ-N6zueymLJ_SsZAqjl1e-TA/edit#gid=0).

However, for some reason when running the checks there are 7 zones that come back as a mismatch between MH and the XREF table. The names are exactly the same so I can not figure out why the check is not working. It does not appear to be a n issue with extra leading or lagging spaces.  

The zones  coming back from the check:
[1] "OFF FLORIDA - NORTH OF 25°20.4' N. LAT."                                            
[2] "ATLANTIC MIGRATORY GROUP KING MACKEREL NORTH OF 34°37.3' N. LAT."                   
[3] "ATLANTIC MIGRATORY GROUP KING MACKEREL SOUTH OF 34°37.3' N. LAT."                   
[4] "TEXAS CLOSURE SHRIMP FISHERY MANAGEMENT AREA -  BEYOND THE 100-FATHOM DEPTH CONTOUR"
[5] NA                                                                                   
[6] "EAST OF 64°34' W. LON. QUEEN CONCH FISHERY MANAGEMENT AREA"                         
[7] "ATLANTIC MIGRATORY GROUP KING MACKEREL NORTH OF 29°25' N. LAT."                     
[8] "ATLANTIC MIGRATORY GROUP KING MACKEREL BETWEEN 29°25' N LAT. AND 28°47'48” N LAT."  

The issue with ZONE = NA was entered as data bugs for 3 records and fixed in the database. The missing zone (SMZ - PA04R on McManus Memorial Reef) was already added to the xref table. Tomorrow, I will upload the most recent MH raw data file which will have those data bugs fixed in the database.
- [ ] Sarina - upload new MH csv file

**Comment by SarinaAtkinson-NOAA** [comment]
@AdyanRios-NOAA this is something I want to discuss during our 11/5 working meeting.

**Comment by SarinaAtkinson-NOAA** [comment]
All xref tables have been turned into csv files so we do not read in Google sheets anymore. It was the Google sheet file encoding that was causing this mismatch in the check. Adyan ran the check on her machine and everything worked now.
